name: Build and deploy ASP.Net Core app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checkout code from repository
      - uses: actions/checkout@v4

      # Setup .NET environment
      - name: Use .NET 6.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      # Install dotnet-ef tool (latest compatible version)
      - name: Install dotnet-ef tool
        run: UseDotNet ./ tools install -l dotnet-ef

      # Build with dotnet
      - name: Build with dotnet
        run: UseDotNet ./ dotnet build --configuration Release

      # Clean and Restore (optional, depends on your project)
      # - name: Clean and Restore
      #   run: |
      #     UseDotNet ./ dotnet clean
      #     UseDotNet ./ dotnet restore

      # Build and Publish
      - name: Build and Publish
        run: UseDotNet ./ dotnet build -c Release && UseDotNet ./ dotnet publish -c Release -o ./publish

      # Apply EF Migrations (adapt path if needed)
      - name: Apply EF Migrations
        run: UseDotNet ./publish dotnet ef database update

      # Upload artifact for deployment job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # Download artifact from build job
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'backendapp23'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7C762B99536F4D9A9CA35A52795867BE }}

