name: Build and deploy ASP.Net Core app to Azure Web App - newbendapp23

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          # Remove dotnet-version to use the version specified in App Service
          include-prerelease: true

      - name: Restore tools and dependencies
        run: |
          dotnet restore
          dotnet tool restore
          
      - name: Build and Publish
        run: |
          dotnet build -c Release
          dotnet publish -c Release -o ./publish
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
   
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
       
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'newbendapp23'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_863EEA8C4D66441EAC9155AD1057472E }}
